### ISSUE TITLE
Remove unnecessary .clone()

### ISSUE THREAD

**Issue by Boscop** [1216892614/Yew-Canvas.rs#1]
Thanks for making this crate, it's very useful :)
Btw, I wanted to see some examples of yew hooks so I read the source, and I noticed it clones `display_size` twice here:
https://github.com/1216892614/Yew-Canvas.rs/blob/e9fef55039cb8819c01d80277c3f9254e9a69a43/src/lib.rs#L92-L96

One clone can be eliminated, right?
```rs
let display_size = display_size.clone();
let (width, height) = display_size.deref();
html! { 
    <canvas 
        style={style} 
        width={width.to_string()} 
        height={height.to_string()} 
```
(Or maybe `.to_string()` isn't even necessary, not sure.)

**Comment by 1216892614** [comment]
Thx, I will fix check and fix soon

**Comment by 1216892614** [comment]
`to_string()` is necessary, `clone` has fixed in [this commit](https://github.com/1216892614/Yew-Canvas.rs/commit/4feac96294c5b8896ceea24e5374dcafe4b92fe1)
